### ISSUE TITLE
Allow for custom root permalink

### ISSUE THREAD

**Issue by defries** [ibericode/wp-knowledge-base#47]
Allowing for either a setting or assigning a page to serve as a root for the knowledge base articles would allow for more flexible URL patterns.  From `/kb/` to `/docs/` for instance.

**Comment by defries** [comment]
Do you have a preference as how to deal with this one @dannyvankooten?

**Comment by dannyvankooten** [comment]
I was thinking of adding a General Settings page where people could (optionally) choose a page to use as their archive. In code, the base slug would automatically be fetched from this page. 

If no page is chosen, maybe show a "slug base" text setting? Much like **Settings > Permalinks** in WordPress itself.

Unless you have a better idea? :)

**Comment by defries** [comment]
I think using a page – and thereby being able to use the content of that page as well – for the root of the KB makes a lot of sense, yeah. Not sure permalink settings are required here, but if you were to consider them, the way WooCommerce uses them would be the way to go IMO.

**Comment by dannyvankooten** [comment]
First stab at this.

![image](https://cloud.githubusercontent.com/assets/885856/12668023/2ac5b0a4-c685-11e5-8d09-2e9c70a0e65f.png)

Allows you to pick a page to use as the archive instead of the default archive template. Choosing a page does the following:

- The page slug will be used as the root permalink
- The page title will be used in breadcrumbs
- The page will be used as the post type archive.

Swag?

**Comment by defries** [comment]
A thing of beauty 😘
